#!/usr/bin/env php
<?php

// app/console

use Wallabag\Reimport\Console\CleanCommand;
use Wallabag\Reimport\Console\CleanAllCommand;
use Symfony\Component\Console\Application;
use Symfony\Component\DependencyInjection\ContainerBuilder;

include(__DIR__ . '/vendor/autoload.php');

$application = new Application();
$application->add(new CleanCommand());
$application->add(new CleanAllCommand());
$application->run();
